version: "3"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "pass"
  postgresql:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "pass"
      POSTGRES_USER: "app"
      POSTGRES_DB: "app"